#!/usr/bin/env bash

APP="phoenix_website" # name of your release
USERNAME="phoenix" # user name on the App Server where the app will be deployed

BUILD_HOST="elixir-build-server.lunarlogic.io" # host where to build the release
BUILD_USER="builder" # local user at build host
BUILD_AT="/tmp/edeliver/$APP/builds" # build directory on build host

STAGING_HOSTS="phoenix-website-staging.lunarlogic.io" # staging / test hosts separated by space
STAGING_USER=$USERNAME # local user at staging hosts

PRODUCTION_HOSTS="phoenix-website.lunarlogic.io" # deploy / production hosts separated by space
PRODUCTION_USER=$USERNAME # local user at deploy hosts

DELIVER_TO="/home/$USERNAME" # deploy directory on production hosts
LINK_SYS_CONFIG="$DELIVER_TO/$APP/$APP.config"

AUTO_VERSION=commit-count+git-revision+branch-unless-master

pre_erlang_get_and_update_deps() {
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      # fail if any command fails (recommended)
      set -e

      cd '$BUILD_AT'

      # required by the phoenix.digest task
      mkdir -p priv/static

      mix deps.get

      npm install

      $BUILD_AT/node_modules/.bin/brunch build --production

      APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
    "
  fi
}
